#!/usr/bin/env python3
"""Build the fixed institutional-source matrix before legal research starts.

The output intentionally marks every row as a *candidate*.  An institutional
portal can establish where to research, but cannot by itself prove a legal rule.
No legal date, benefit or card is generated by this file.
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "auditoria" / "execucoes" / "reconstrucao-provas-2026-07-16"

SEFAZ = {
    "AC": "https://www.sefaz.ac.gov.br/legislacao/",
    "AL": "https://www.sefaz.al.gov.br/legislacao",
    "AM": "https://online.sefaz.am.gov.br/silt/",
    "AP": "https://virtual.sefaz.ap.gov.br/portal/",
    "BA": "https://www.sefaz.ba.gov.br/legislacao/",
    "CE": "https://www.sefaz.ce.gov.br/legislacao-tributaria/",
    "DF": "https://ww1.receita.fazenda.df.gov.br/legislacao/pesquisa-avancada",
    "ES": "https://www3.sefaz.es.gov.br/legislacao/",
    "GO": "https://goias.gov.br/economia/legislacao-tributaria/",
    "MA": "https://sistemas1.sefaz.ma.gov.br/portalsefaz/jsp/pagina/pagina.jsf?codigo=95",
    "MG": "https://www.fazenda.mg.gov.br/empresas/legislacao_tributaria/",
    "MS": "https://www.sefaz.ms.gov.br/legislacao/",
    "MT": "https://app1.sefaz.mt.gov.br/Sistema/legislacao/legislacaotribut.nsf/",
    "PA": "https://www.sistemas.pa.gov.br/sisleis/legislacao/",
    "PB": "https://www.sefaz.pb.gov.br/legislacao",
    "PE": "https://www.sefaz.pe.gov.br/Legislacao/",
    "PI": "https://portal.sefaz.pi.gov.br/legislacao/",
    "PR": "https://www.legislacao.pr.gov.br/legislacao/pesquisarAto.do?action=iniciarProcesso",
    "RJ": "https://portal.fazenda.rj.gov.br/icms/",
    "RN": "https://www.set.rn.gov.br/contentProducao/aplicacao/set_v2/legislacao/legislacao.asp",
    "RO": "https://legislacao.sefin.ro.gov.br/",
    "RR": "https://www.sefaz.rr.gov.br/downloads/legislacao",
    "RS": "https://estado.rs.gov.br/legislacao",
    "SC": "https://legislacao.sef.sc.gov.br/",
    "SE": "http://legislacaoonline.sefaz.se.gov.br:17501/Paginas/Default.aspx",
    "SP": "https://portal.fazenda.sp.gov.br/paginas/legislacao.aspx",
    "TO": "https://www.to.gov.br/sefaz/legislacao-tributaria/3lb4r1ekdyvb",
}

DOE = {
    "AC": "https://diario.ac.gov.br/",
    "AL": "https://diario.imprensaoficial.al.gov.br/",
    "AM": "https://diario.imprensaoficial.am.gov.br/",
    "AP": "https://diofe.portal.ap.gov.br/",
    "BA": "https://dool.egba.ba.gov.br/",
    "CE": "https://www.ce.gov.br/diario-oficial/",
    "DF": "https://www.dodf.df.gov.br/",
    "ES": "https://ioes.dio.es.gov.br/portal/visualizacoes/diario_oficial",
    "GO": "https://www.diariooficial.abc.go.gov.br/",
    "MA": "https://www.diariooficial.ma.gov.br/",
    "MG": "https://www.jornalminasgerais.mg.gov.br/",
    "MS": "https://www.spdo.ms.gov.br/DiarioDOE/Index/Index/",
    "MT": "https://www.iomat.mt.gov.br/",
    "PA": "http://www.ioepa.com.br/pesquisa",
    "PB": "https://auniao.pb.gov.br/servicos/doe",
    "PE": "https://www.cepe.com.br/diario-oficial",
    "PI": "https://www.diario.pi.gov.br/doe/",
    "PR": "https://dioe.pr.gov.br/portal/pages/display",
    "RJ": "https://www.ioerj.com.br/",
    "RN": "https://diariooficial.rn.gov.br/",
    "RO": "https://diof.ro.gov.br/",
    "RR": "https://imprensaoficial.rr.gov.br/",
    "RS": "https://www.diariooficial.rs.gov.br/",
    "SC": "https://portal.doe.sea.sc.gov.br/",
    "SE": "https://iose.se.gov.br/",
    "SP": "https://doe.sp.gov.br/",
    "TO": "https://diariooficial.to.gov.br/",
}

ASSEMBLEIA = {
    "AC": "https://www.al.ac.leg.br/",
    "AL": "https://www.al.al.leg.br/",
    "AM": "https://www.aleam.gov.br/",
    "AP": "https://www.al.ap.gov.br/",
    "BA": "https://www.al.ba.gov.br/",
    "CE": "https://www.al.ce.gov.br/",
    "DF": "https://www.cl.df.gov.br/leis",
    "ES": "https://www3.al.es.gov.br/legislacao/consulta-legislacao.aspx",
    "GO": "https://transparencia.al.go.leg.br/legislacoes",
    "MA": "https://www.al.ma.leg.br/",
    "MG": "https://www.almg.gov.br/atividade-parlamentar/leis/legislacao-mineira",
    "MS": "https://al.ms.gov.br/",
    "MT": "https://diariooficial.al.mt.gov.br/",
    "PA": "https://www.alepa.pa.gov.br/",
    "PB": "https://www.al.pb.leg.br/",
    "PE": "https://www.alepe.pe.gov.br/",
    "PI": "https://www.al.pi.leg.br/",
    "PR": "https://consultas.assembleia.pr.leg.br/",
    "RJ": "https://www3.alerj.rj.gov.br/lotus_notes/default.asp?id=144",
    "RN": "https://www.al.rn.leg.br/",
    "RO": "https://www.al.ro.leg.br/",
    "RR": "https://al.rr.leg.br/",
    "RS": "https://ww4.al.rs.gov.br/legislacao-estadual",
    "SC": "https://leis.alesc.sc.gov.br/",
    "SE": "https://al.se.leg.br/",
    "SP": "https://www.al.sp.gov.br/norma/resultados?idsTipoNorma=9&tipoPesquisa=E",
    "TO": "https://www.al.to.leg.br/",
}

FEDERAL = {
    "PLANALTO": "https://www.planalto.gov.br/ccivil_03/leis/_lei-principal.htm",
    "DOU_IMPRENSA_NACIONAL": "https://www.in.gov.br/leiturajornal",
    "RFB_NORMAS": "https://normas.receita.fazenda.gov.br/sijut2consulta/consulta.action",
    "PGFN": "https://www.gov.br/pgfn/pt-br/assuntos/representacao-judicial/legislacao-e-normas",
    "CONFAZ_CONVENIOS_ICMS": "https://www.confaz.fazenda.gov.br/legislacao/convenios",
    "CONFAZ_AJUSTES_SINIEF": "https://www.confaz.fazenda.gov.br/legislacao/ajustes",
    "CONFAZ_ATOS_COTEPE": "https://www.confaz.fazenda.gov.br/legislacao/atos",
    "CONFAZ_PROTOCOLOS_ICMS": "https://www.confaz.fazenda.gov.br/legislacao/protocolos",
    "CONFAZ_RESOLUCOES": "https://www.confaz.fazenda.gov.br/legislacao/resolucoes",
    "CGIBS_REGULAMENTOS": "https://www.cgibs.gov.br/regulamentos",
    "PORTAL_NACIONAL_TCBS": "https://consumo.tributos.gov.br/",
    "SENADO": "https://www25.senado.leg.br/web/atividade/legislacao/legislacao-federal",
    "STF": "https://portal.stf.jus.br/jurisprudencia/",
    "STJ": "https://processo.stj.jus.br/SCON/",
    "CARF": "https://www.gov.br/carf/pt-br/jurisprudencia",
}


def url_domain(url: str) -> str:
    return url.split("//", 1)[1].split("/", 1)[0].lower()


def rows() -> list[dict[str, str]]:
    result: list[dict[str, str]] = []
    for uf in sorted(SEFAZ):
        for source_class, mapping in (
            ("SEFAZ_LEGISLACAO", SEFAZ),
            ("DOE", DOE),
            ("ASSEMBLEIA_LEGISLATIVA", ASSEMBLEIA),
        ):
            url = mapping[uf]
            result.append({
                "source_id": f"{uf}::{source_class}",
                "jurisdicao": uf,
                "classe": source_class,
                "url_inicial": url,
                "url_final": "",
                "dominio_oficial_esperado": url_domain(url),
                "status_http": "",
                "sha256_corpo": "",
                "receipt_id": "",
                "status_prova": "PENDENTE_DE_CAPTURA",
                "observacao": "Fonte institucional candidata; não é prova de regra até leitura do ato.",
            })
    for family, url in FEDERAL.items():
        result.append({
            "source_id": f"BR::{family}",
            "jurisdicao": "BR",
            "classe": family,
            "url_inicial": url,
            "url_final": "",
            "dominio_oficial_esperado": url_domain(url),
            "status_http": "",
            "sha256_corpo": "",
            "receipt_id": "",
            "status_prova": "PENDENTE_DE_CAPTURA",
            "observacao": "Fonte institucional candidata; não é prova de regra até leitura do ato.",
        })
    return result


def write_yaml(rows_: list[dict[str, str]], output: Path) -> None:
    lines = [
        "versao: 1",
        "finalidade: 'Matriz institucional de descoberta; não prova norma individual.'",
        "regras:",
        "  - 'Portal ou índice não é prova material de regra.'",
        "  - 'Aprovação exige ato, trecho, localizador e refetch independente.'",
        "fontes:",
    ]
    for row in rows_:
        lines.extend([
            f"  - id: '{row['source_id']}'",
            f"    jurisdicao: '{row['jurisdicao']}'",
            f"    classe: '{row['classe']}'",
            f"    url_inicial: '{row['url_inicial']}'",
            "    status_prova: 'PENDENTE_DE_CAPTURA'",
        ])
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, default=OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    all_rows = rows()
    state_rows = [row for row in all_rows if row["jurisdicao"] != "BR"]
    if len(state_rows) != 81 or len({row["source_id"] for row in all_rows}) != len(all_rows):
        raise SystemExit("Matriz canônica inválida: exige 81 linhas estaduais e IDs únicos.")
    if any(uf not in DOE or uf not in ASSEMBLEIA for uf in SEFAZ):
        raise SystemExit("Matriz canônica inválida: classe estadual ausente.")
    if args.check:
        print(f"OK: {len(state_rows)} linhas estaduais e {len(all_rows) - len(state_rows)} famílias federais.")
        return 0
    args.output_dir.mkdir(parents=True, exist_ok=True)
    fields = list(all_rows[0])
    with (args.output_dir / "matriz_fontes_canonicas.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(all_rows)
    write_yaml(all_rows, args.output_dir / "escopo_fontes_canonico.yaml")
    print(f"Gerados {len(all_rows)} registros em {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
